### ISSUE TITLE
modificar documentacion

### ISSUE THREAD

**Issue by Natalia24v** [Natalia24v/TurnowApp#2]
revisar y modificar requerimientos en archivo ieee830

**Comment by nataliaruiz04** [comment]
Se actualizó documento ieee 830.

**Comment by lanusroots** [comment]
Actualización del IEEE-830 (detalle de los requisitos específicos de la app)

**Comment by lanusroots** [comment]
Actualización del IEEE-830 (detalle de los requisitos específicos de la app)

**Comment by RochettiUriel** [comment]
Actualizacion de IEEE830 (Agrego requisitos de hardware para el proyecto)

**Comment by guillevla** [comment]
Actualizacion de IEE830 - Agregado perspectiva de producto y revision formatos de texto. 
[ieee-830 turnow.docx](https://github.com/Natalia24v/TurnowApp/files/12532469/ieee-830.turnow.docx)
